root@AirTouch-AP-PSK:~# cat send_certs.sh                                                                                                                                                                                                                    
#!/bin/bash                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                             
# DO NOT COPY                                                                                                                                                                                                                                                
# Script to sync certs-backup folder to AirTouch-office.                                                                                                                                                                                                     
                                                                                                                                                                                                                                                             
# Define variables                                                                                                                                                                                                                                           
REMOTE_USER="remote"                                                                                                                                                                                                                                         
REMOTE_PASSWORD="xGgWEwqUpfoOVsLeROeG"                                                                                                                                                                                                                       
REMOTE_PATH="~/certs-backup/"                                                                                                                                                                                                                                
LOCAL_FOLDER="/root/certs-backup/"                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                             
# Use sshpass to send the folder via SCP                                                                                                                                                                                                                     
sshpass -p "$REMOTE_PASSWORD" scp -r "$LOCAL_FOLDER" "$REMOTE_USER@10.10.10.1:$REMOTE_PATH"       