[libdefaults]
    default_realm = CHECKPOINT.HTB
    dns_lookup_realm = false
    dns_lookup_kdc = false

[realms]
    CHECKPOINT.HTB = {
        kdc = dc01.checkpoint.htb
        admin_server = dc01.checkpoint.htb
    }

[domain_realm]
    .checkpoint.htb = CHECKPOINT.HTB
    checkpoint.htb = CHECKPOINT.HTB
